apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-backend
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Release.Name }}-backend
spec:
  replicas: {{ .Values.replicas.backend }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-backend
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-backend
    spec:
      containers:
        - name: backend
          image: "{{ .Values.registry }}/{{ .Values.backend.image }}:{{ .Values.backend.tag }}"
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: {{ .Values.service.backend.targetPort }}
          envFrom:
            - configMapRef:
                name: task-manager-env
          resources:
            {{- toYaml .Values.resources.backend | nindent 12 }}
