{{- if .Values.backend.envConfigMap }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: task-manager-env
  namespace: {{ .Values.namespace }}
data:
  {{- range $key, $value := .Values.backend.envConfigMap }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
{{- end }}

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: task-manager-web-config
  namespace: {{ .Values.namespace }}
data:
  config.json: |
    {
      "API_BASE_URL": "https://task-api.aprilpollo.com",
      "GOOGLE_OAUTH_URL": "",
      "GOOGLE_CLIENT_ID": "",
      "GOOGLE_REDIRECT_URI": ""
    }
