apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-postgres
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Release.Name }}-postgres
spec:
  replicas: {{ .Values.replicas.postgres }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-postgres
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-postgres
    spec:
      containers:
        - name: postgres
          image: "{{ .Values.registry }}/{{ .Values.postgres.image }}:{{ .Values.postgres.tag }}"
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: {{ .Values.service.postgres.targetPort }}
          envFrom:
            - configMapRef:
                name: task-manager-env
          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgresql/data
          resources:
            {{- toYaml .Values.resources.postgres | nindent 12 }}
      volumes:
        - name: postgres-data
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-postgres-pvc
